spring:
  profiles:
    active: release

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: me.zhiyao.bing.dao.model
  global-config:
    db-config:
      table-prefix: t_
