spring:
  profiles:
    active: release
  mail:
    host:
    port:
    username:
    password:
    from:
    to:
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          socketFactory:
            port: 465
            fallback: false
            class: javax.net.ssl.SSLSocketFactory

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: me.zhiyao.bing.dao.model
  global-config:
    db-config:
      table-prefix: t_
